### ISSUE TITLE
Error with Deuterium recipe

### ISSUE THREAD

**Issue by achman741** [wokdok/AddAmountOfRecipePer1min#1]
When i was looking through the tech tree i hovered over the deuterium recipe and got a error, probably related to the 1% recipe on it. The deuterium recipe stays on screen until restart from the tech tree, doesn't stay on the screen when looking at the recipe in the crafting menu, still gives error though

Error from tech screen:
![dsp error](https://user-images.githubusercontent.com/4545011/111874867-68587400-896d-11eb-8f7c-8191a7776e54.PNG)
Error from crafting menu:
![dsp error 2](https://user-images.githubusercontent.com/4545011/111875019-051b1180-896e-11eb-8eac-430e48ff96ce.PNG)

**Comment by achman741** [comment]
Have other mods installed as well, can give list if needed, I can cause the error the tech screen consistently but i tried to cause it from the crafting menu again but it didn't occur again until fresh restart for some reason.

**Comment by wokdok** [comment]
thank you report issue.

I'll fix it.

**Comment by wokdok** [comment]
@achman741 I uploaded 1.1.1.
It fixes your report error.

thank you.
