### ISSUE TITLE
When mousing over coal in a miner the tooltip freezes on my screen, causses error and big fps hit

### ISSUE THREAD

**Issue by Malchron** [wokdok/AddAmountOfRecipePer1min#2]
![image](https://user-images.githubusercontent.com/76578407/112352781-737b0f00-8ca1-11eb-9769-f4a40cbfd1ac.png)

On version 1.2 of your mod

These are my other mods 
![image](https://user-images.githubusercontent.com/76578407/112352861-8857a280-8ca1-11eb-8392-8448670e8e7b.png)

**Comment by wokdok** [comment]
thank you report issue.
I fixed it in 1.2.1.
